language: node_js

node_js:
  - "8"
sudo: required

services:
  - docker

after_deploy:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "ap-northeast-2"
  app: "iotjs-app-eb"
  env: "iotjs-app-eb-dev"
  bucket_name: "test-elastic-beanstalk"
  on:
    branch: master
